name: Deploy to NuGet

on:
  push:
    branches: [master]
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Setup .NET'
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: 'Restore packages'
        run: dotnet restore

      - name: 'Build project'
        run: dotnet build --no-restore --configuration Release

      - name: 'Test'
        run: dotnet test --no-build

      - name: 'Pack project'
        run: dotnet pack --no-build --output nupkg

      - name: 'Push to NuGet'
        run: dotnet nuget push .\nupkg\*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
